### ISSUE TITLE
Datepicker won't select date on mobile (iOS at least) if datepicker is in a modal window

### ISSUE THREAD

**Issue by aaronjpitts** [tristen/datepickr#10]
Hi,

I'm using your datepicker here: http://papayapods.com (it's brilliant, thanks). You will see I use it for the move-in and move-out dates. On mobile when I select a date it doesn't do anything when it is in this modal window, works fine on desktop. Any ideas or solutions?

Many thanks

**Comment by aaronjpitts** [comment]
Actually it had nothing to do with being in a modal window. It is a problem with your code. In safari 9 and ios it doesn't work because of line 84

```
            Object.keys(daylinks).forEach(function (akey) {
                daylinks[akey].classList.remove('active', 'halfday');
            });
```

It gives the following error: TypeError: undefined is not an object (evaluating 'daylinks[akey].classList.remove')

By changing the above to:

```
            for (i = 0; i < daylinks.length; i++) { 
                daylinks[i].classList.remove('active', 'halfday');
            }
```

It works. Can you please change this your end for future releases? Thanks anyway, it's a great plugin!

**Comment by tristen** [comment]
Hi @aaronjpitts - would you consider submitting this as a pull request? I'd happily merge it!

**Comment by aaronjpitts** [comment]
@tristen I'd be happy to, but I cannot seem to use your make file to build to dist. Editing index.js and running 'make' just gives: Nothing to be done for `all'. How must I use it? thanks

**Comment by aaronjpitts** [comment]
Or must I edit the datepickr.js in dist directly too?

**Comment by tristen** [comment]
Oh there should be a deletion command in that Makefile. @aaronjpitts just a pr for the change in index.js is great. I can bundle this and publish a new version.

**Comment by aaronjpitts** [comment]
Sorry but I just get 'ERROR: Permission to tristen/datepickr.git denied to aaronjpitts.' when trying to push my new branch to yours for a pull request

**Comment by tristen** [comment]
@aaronjpitts if you fork datepickr to your own account you can submit a pull request from `aaronjpitts/datepickr.git` to `tristen/datepickr.git`

**Comment by aaronjpitts** [comment]
PR sent :)

**Comment by tristen** [comment]
Woot! Closed via https://github.com/tristen/datepickr/pull/11
